arch:
    - amd64
    - ppc64le
language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt 
  - pip install mypy

script:
  - MYPYPATH=./stubs mypy --config-file mypy.conf irc.py
  - python3 -m tests
